// ============================================================
// registry/index.ts — 全局注册表 barrel re-export
// 所有外部模块通过 import from '../game/registry' 访问
// ============================================================

export type {
  ItemCategory, ItemRarity, ItemDef,
  RecipeQuality, EquipSlot, EquipStatBonus, EquipDef,
  RecipeDef, SmithingRecipeDef,
  BreakthroughItemCost, BreakthroughCondition, BreakthroughReqDef,
  TribulationWave, TribulationDef,
  TechniqueType, TechniqueRarity, TechniqueStatBonus, TechniqueDef, PassiveEffect,
  EventCategory, EventTone, GameEvent,
  DLCPack,
  DeathSeverity, DeathTriggerDef, DeathPenaltyDef, LifeSaverDef, RevivalMethodDef, DeathSystemState,
  MonsterDef,
  ElementType, DivineArtDef, DivineArtSkillEffect,
  BodyRealmDef, SpiritRootBodyBonus,
  RealmDef,
  RegionDef, MapSystemState,
  BottleneckDef, BottleneckUnlockMethod, BottleneckState,
  NpcDef, NpcDisposition, NpcRole, NpcPersonality, NpcRelation, NpcRelationLevel, NpcSystemState,
  QuestObjectiveType, QuestObjective, QuestReward, QuestStep, QuestChainCondition,
  QuestChainCategory, QuestChainDef, QuestObjectiveProgress, QuestChainProgress,
  QuestStatus, QuestSystemState, QuestTrigger,
  DialogueNodeType, DialogueEffect, DialogueChoiceCondition, DialogueChoice,
  DialogueNode, DialogueCondition, DialogueChainDef, DialogueSystemState, IdleChatPool,
  JsonEventCondition, VarConstraint, EventTemplate, VariableEntry, VariablePool, ProceduralEventState,
  AffixPosition, ProceduralEquipQuality, EquipBaseTemplate, AffixDef, GeneratedEquipInstance, ProceduralItemState,
  MutationType, MonsterTemplate, MutationDef, ProceduralMonsterState,
  TechniqueTraitDef, TechniqueTraitTier, TechniqueTraitSlot, TechniqueInstance,
  TechniqueQualityConfig, ProceduralTechniqueState,
  RealmTier, AscensionDef, AscensionItemCost, AscensionCondition, AscensionState,
  RankingBoardKind, RankingScoreKey, RankingDimensionDef, RankingEntry, RankingSnapshot, RankingSystemState,
  DestinyRarity, DestinyTalentStatKey, DestinyTalentEffect, DestinyDef, TalentDef, TalentTreeNodeDef, DestinyTalentState, UnlockTalentNodeResult,
  BountyObjectiveType, BountyObjectiveDef, BountyTemplateDef, GeneratedBounty, ActiveBounty, BountySystemState,
  SecretRealmStageType, SecretRealmStageDef, SecretRealmDef, SecretRealmRun, SecretRealmSystemState,
  Alignment, KarmaSystemState, EnlightenmentInsightDef, EnlightenmentState, EnlightenmentBuff,
  SectDef, SectRankDef, SectMissionDef, SectStoreItemDef, SectFacilityDef, SectSystemState, SectManagementState, SectMemberState,
} from '../types';
export type {
  AchievementCategory, AchievementDef, AchievementBonusStats,
  AchievementRecalcBonus, AchievementOnceBonus, AchievementSystemState,
} from '../achievement/types';

export { registerDLC, unregisterDLC, getDLC, getAllDLCs } from './dlc';
export { clearAllRegistries } from './stores';
export {
  registerEvent, registerEvents, getEvent, getEventsByCategory,
  getItemDef, getItemDefsByCategory, getAllItemDefs,
  getRecipe, getAllRecipes,
  getEquipDef, getAllEquipDefs,
  getSmithingRecipe, getAllSmithingRecipes,
  getBreakthroughReq, getTribulationDef, getTribulationById,
  getTechniqueDef, getAllTechniqueDefs,
  getDeathTrigger, getAllDeathTriggers,
  getLifeSaver, getAllLifeSavers,
  getRevivalMethod, getAllRevivalMethods,
  getMonster, getAllMonsters, getMonstersByRealm,
  getDivineArtDef, getAllDivineArtDefs, getDivineArtsByElement,
  getAchievement, getAllAchievementDefs,
  getBodyRealmDef, getAllBodyRealmDefs,
  getSpiritRootBodyBonus, getAllSpiritRootBodyBonuses,
  getRealmDef, getAllRealmDefs, getMaxRealmIndex,
  getRegion, getAllRegions,
  getBottleneckDef, getAllBottleneckDefs, getBottlenecksForRealm, getBottlenecksForBodyRealm, getBottlenecksForTechnique,
  getNpcDef, getAllNpcDefs, getNpcsByRegionTags, getNpcsByRole, getNpcsByDisposition,
  getQuestChainDef, getAllQuestChainDefs, getQuestChainsByCategory,
  getDialogueDef, getAllDialogueDefs, getDialoguesByNpc, getIdleChatPool,
  getEventTemplate, getAllEventTemplates, getEventTemplatesByCategory,
  getVariablePool, getAllVariablePools, getVariablePoolsByVariable,
  getEquipTemplate, getAllEquipTemplates, getEquipTemplatesBySlot,
  getAffixDef, getAllAffixDefs, getAffixesByPosition,
  getGeneratedEquip, registerGeneratedEquip, removeGeneratedEquip, getAllGeneratedEquips, clearAllGeneratedEquips,
  getMonsterTemplate, getAllMonsterTemplates, getMonsterTemplatesByRealm,
  getMutationDef, getAllMutationDefs, getMutationDefsByType,
  getTechniqueTraitDef, getAllTechniqueTraitDefs, getTechniqueTraitsByTier,
  getTechniqueInstance, registerTechniqueInstance, removeTechniqueInstance, getAllTechniqueInstances, clearAllTechniqueInstances,
  getAscensionDef, getAllAscensionDefs, getAscensionForRealm,
  getRankingDimensionDef, getAllRankingDimensionDefs, getRankingDimensionsByBoard,
  getDestinyDef, getAllDestinyDefs, getTalentDef, getAllTalentDefs, getTalentTreeNodeDef, getAllTalentTreeNodeDefs,
  getBountyTemplateDef, getAllBountyTemplateDefs,
  getSecretRealmDef, getAllSecretRealmDefs,
  getEnlightenmentInsightDef, getAllEnlightenmentInsightDefs,
  getSectDef, getAllSectDefs,
} from './queries';
export {
  triggerEvent, resetRuntimeState, saveEventState, loadEventState,
} from './event-engine';
export type { EventResult, EventRuntimeState } from './event-engine';
