// ============================================================
// achievement/data.ts — 核心成就列表（26 条，T0031）
// ============================================================

import type { AchievementDef } from './types';

export const CORE_ACHIEVEMENTS: AchievementDef[] = [
  // ── 战斗 ──
  {
    id: 'core:first_blood',
    name: '初战之人',
    description: '击败第一只妖兽',
    category: 'combat',
    icon: '⚔️',
    condition: (p) => p.tracking.killCount >= 1,
    bonusStats: { atk: 1 },
    bonusDescription: '攻击 +1',
  },
  {
    id: 'core:beast_slayer_50',
    name: '妖兽猎手',
    description: '累计击杀 50 只妖兽',
    category: 'combat',
    icon: '🗡️',
    condition: (p) => p.tracking.killCount >= 50,
    bonusStats: { atk: 3 },
    bonusDescription: '攻击 +3',
  },
  {
    id: 'core:beast_slayer_100',
    name: '百战老将',
    description: '累计击杀 100 只妖兽',
    category: 'combat',
    icon: '🏹',
    condition: (p) => p.tracking.killCount >= 100,
    bonusStats: { atk: 5 },
    bonusDescription: '攻击 +5',
  },
  {
    id: 'core:beast_slayer_1000',
    name: '千杀屠魔',
    description: '累计击杀 1000 只妖兽',
    category: 'combat',
    icon: '💀',
    condition: (p) => p.tracking.killCount >= 1000,
    bonusStats: { atk: 15, def: 5 },
    bonusDescription: '攻击 +15，防御 +5',
    hidden: true,
  },
  {
    id: 'core:boss_hunter_10',
    name: '精英猎手',
    description: '击杀 10 只精英妖兽',
    category: 'combat',
    icon: '👑',
    condition: (p) => p.tracking.bossKillCount >= 10,
    bonusStats: { atk: 5, def: 5 },
    bonusDescription: '攻击 +5，防御 +5',
  },
  {
    id: 'core:higher_realm_victory',
    name: '以弱胜强',
    description: '击败境界高于自己的敌人',
    category: 'combat',
    icon: '🔥',
    condition: (p) => p.tracking.defeatedHigherRealm === true,
    bonusStats: { atk: 3, def: 3 },
    bonusDescription: '攻击 +3，防御 +3',
  },
  {
    id: 'core:near_death_survivor',
    name: '九死一生',
    description: '在战斗中 HP 降至 10 以下仍然存活',
    category: 'combat',
    icon: '💗',
    condition: (p) => p.tracking.hasBeenBelow10Hp === true,
    bonusStats: { hp: 20 },
    bonusDescription: '气血上限 +20',
  },

  // ── 修炼 ──
  {
    id: 'core:qi_condensation',
    name: '筑基有成',
    description: '突破至第一境界',
    category: 'cultivation',
    icon: '🌱',
    condition: (p) => p.realmIndex >= 1,
    bonusStats: { hp: 10 },
    bonusDescription: '气血上限 +10',
  },
  {
    id: 'core:golden_core',
    name: '金丹道人',
    description: '突破至金丹境',
    category: 'cultivation',
    icon: '🌕',
    condition: (p) => p.realmIndex >= 3,
    bonusStats: { hp: 20, mp: 10 },
    bonusDescription: '气血上限 +20，灵力上限 +10',
  },
  {
    id: 'core:nascent_soul',
    name: '元婴天骄',
    description: '突破至元婴境',
    category: 'cultivation',
    icon: '⭐',
    condition: (p) => p.realmIndex >= 4,
    bonusStats: { hp: 30, mp: 20, atk: 5 },
    bonusDescription: '气血 +30，灵力 +20，攻击 +5',
  },
  {
    id: 'core:tribulation_survived',
    name: '天劫渡世',
    description: '成功渡过至少一次天劫',
    category: 'cultivation',
    icon: '⚡',
    condition: (p) => ((p.systems?.breakthrough as { tribulationsPassed?: unknown[] } | undefined)?.tribulationsPassed?.length ?? 0) >= 1,
    bonusStats: { hp: 20, mp: 10 },
    bonusDescription: '气血 +20，灵力 +10',
  },
  {
    id: 'core:breakthrough_stubborn',
    name: '百折不挠',
    description: '连续突破失败 3 次以上',
    category: 'cultivation',
    icon: '💪',
    condition: (p) => (p.tracking.consecutiveBreakthroughFails ?? 0) >= 3,
    bonusStats: { comprehension: 5 },
    bonusDescription: '悟性 +5（一次性）',
  },
  {
    id: 'core:cultivate_streak',
    name: '修炼痴人',
    description: '连续修炼 10 次',
    category: 'cultivation',
    icon: '🧘',
    condition: (p) => (p.tracking.consecutiveCultivates ?? 0) >= 10,
    bonusStats: { hp: 5 },
    bonusDescription: '气血上限 +5',
  },
  {
    id: 'core:centenarian',
    name: '百岁长者',
    description: '年龄达到 100 岁',
    category: 'cultivation',
    icon: '🎂',
    condition: (p) => p.age >= 1200,
    bonusStats: { lifespan: 600 },
    bonusDescription: '寿元 +50年（一次性）',
  },

  // ── 炼丹 ──
  {
    id: 'core:first_pill',
    name: '丹道入门',
    description: '成功炼制第一枚丹药',
    category: 'alchemy',
    icon: '💊',
    condition: (p) => ((p.systems?.alchemy as { totalCrafted?: number } | undefined)?.totalCrafted ?? 0) >= 1,
    bonusStats: { mentalPower: 5 },
    bonusDescription: '念力上限 +5',
  },
  {
    id: 'core:pill_master_50',
    name: '丹道精通',
    description: '累计炼制 50 枚丹药',
    category: 'alchemy',
    icon: '🔮',
    condition: (p) => ((p.systems?.alchemy as { totalCrafted?: number } | undefined)?.totalCrafted ?? 0) >= 50,
    bonusStats: { mentalPower: 10 },
    bonusDescription: '念力上限 +10',
  },
  {
    id: 'core:pill_excellent',
    name: '极品丹师',
    description: '炼制出至少一枚极品丹药',
    category: 'alchemy',
    icon: '✨',
    condition: (p) => ((p.systems?.alchemy as { excellentCount?: number } | undefined)?.excellentCount ?? 0) >= 1,
    bonusStats: { mentalPower: 5 },
    bonusDescription: '念力上限 +5',
  },
  {
    id: 'core:pill_grandmaster',
    name: '丹道宗师',
    description: '累计炼制 200 枚丹药',
    category: 'alchemy',
    icon: '🌟',
    condition: (p) => ((p.systems?.alchemy as { totalCrafted?: number } | undefined)?.totalCrafted ?? 0) >= 200,
    bonusStats: { mentalPower: 20, luck: 3 },
    bonusDescription: '念力上限 +20，幸运 +3（一次性）',
    hidden: true,
  },

  // ── 收集 ──
  {
    id: 'core:first_gold',
    name: '初获灵石',
    description: '拥有 100 枚灵石',
    category: 'collection',
    icon: '💰',
    condition: (p) => p.gold >= 100,
    bonusStats: { luck: 1 },
    bonusDescription: '幸运 +1（一次性）',
  },
  {
    id: 'core:wealthy',
    name: '万贯家财',
    description: '拥有 10000 枚灵石',
    category: 'collection',
    icon: '💎',
    condition: (p) => p.gold >= 10000,
    bonusStats: { luck: 3, charisma: 2 },
    bonusDescription: '幸运 +3，魅力 +2（一次性）',
  },
  {
    id: 'core:item_collector',
    name: '收藏家',
    description: '背包同时持有 10 种物品',
    category: 'collection',
    icon: '🎁',
    condition: (p) => p.inventory.length >= 10,
    bonusStats: { charisma: 2 },
    bonusDescription: '魅力 +2（一次性）',
  },
  {
    id: 'core:technique_scholar',
    name: '功法博学',
    description: '同时习得 3 种功法',
    category: 'collection',
    icon: '📚',
    condition: (p) => p.techniques.length >= 3,
    bonusStats: { atk: 5, def: 5 },
    bonusDescription: '攻击 +5，防御 +5',
  },
  {
    id: 'core:equipment_hoarder',
    name: '装备达人',
    description: '同时佩戴 5 件装备',
    category: 'collection',
    icon: '⚔️',
    condition: (p) => Object.values(p.equipped).filter(Boolean).length >= 5,
    bonusStats: { def: 5 },
    bonusDescription: '防御 +5',
  },

  // ── 综合 ──
  {
    id: 'core:first_year',
    name: '踏上修途',
    description: '在修仙之路上走过第一年',
    category: 'misc',
    icon: '🌸',
    condition: (p) => (p.gameYear ?? 1) >= 2,
    bonusStats: { luck: 1 },
    bonusDescription: '幸运 +1（一次性）',
  },
  {
    id: 'core:near_death_escape',
    name: '死里逃生',
    description: '经历死亡后成功复活',
    category: 'misc',
    icon: '🕊️',
    condition: (p) => ((p.systems?.death as { revivalCount?: number } | undefined)?.revivalCount ?? 0) >= 1,
    bonusStats: { hp: 10 },
    bonusDescription: '气血上限 +10',
  },
  {
    id: 'core:inner_demon_survivor',
    name: '心魔征服',
    description: '心情低迷 5 次后重新振作',
    category: 'misc',
    icon: '🧿',
    condition: (p) => (p.tracking.lowMoodStreak ?? 0) >= 5 && p.mood > 50,
    bonusStats: { luck: 2 },
    bonusDescription: '幸运 +2（一次性）',
    hidden: true,
  },
  {
    id: 'core:full_inventory',
    name: '背囊充盈',
    description: '背包达到容量上限',
    category: 'misc',
    icon: '🎒',
    condition: (p) => p.inventory.length >= p.inventoryCapacity,
    bonusStats: { luck: 1 },
    bonusDescription: '幸运 +1（一次性）',
  },
];
